/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Alexandru
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        eMostrar = new javax.swing.JTextArea();
        bLlegirText = new javax.swing.JButton();
        bPalindroms = new javax.swing.JButton();
        bSenseRepetits = new javax.swing.JButton();
        bOrdenats = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bParaules = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bVisualitzarOrdenats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eMostrar.setEditable(false);
        eMostrar.setColumns(20);
        eMostrar.setRows(5);
        jScrollPane1.setViewportView(eMostrar);

        bLlegirText.setText("Llegir Text");

        bPalindroms.setText("Visualitzar Palindroms");
        bPalindroms.setActionCommand("Palindroms");
        bPalindroms.setEnabled(false);

        bSenseRepetits.setText("Visualitzar sense repetits");
        bSenseRepetits.setActionCommand("Repetits");
        bSenseRepetits.setEnabled(false);

        bOrdenats.setText("Ordena Llista");
        bOrdenats.setToolTipText("");
        bOrdenats.setActionCommand("Ordenats");
        bOrdenats.setEnabled(false);

        bExit.setText("Exit");

        bBorrar.setText("Borrar Paraules");
        bBorrar.setActionCommand("Borrar");
        bBorrar.setEnabled(false);

        bParaules.setText("Visualitzar Paraules");
        bParaules.setActionCommand("Paraules");
        bParaules.setEnabled(false);

        bClear.setText("Borrar Visualització");
        bClear.setEnabled(false);

        bVisualitzarOrdenats.setText("Visualitzar Ordenats");
        bVisualitzarOrdenats.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bLlegirText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPalindroms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bParaules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSenseRepetits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bOrdenats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVisualitzarOrdenats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLlegirText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bParaules)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPalindroms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSenseRepetits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVisualitzarOrdenats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bOrdenats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(bExit))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }
    
    public void setOidor(ActionListener oidor) {
        bLlegirText.addActionListener(oidor);
        bOrdenats.addActionListener(oidor);
        bPalindroms.addActionListener(oidor);
        bSenseRepetits.addActionListener(oidor);
        bBorrar.addActionListener(oidor);
        bExit.addActionListener(oidor);
        bParaules.addActionListener(oidor);
        bClear.addActionListener(oidor);
        bVisualitzarOrdenats.addActionListener(oidor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bLlegirText;
    private javax.swing.JButton bOrdenats;
    private javax.swing.JButton bPalindroms;
    private javax.swing.JButton bParaules;
    private javax.swing.JButton bSenseRepetits;
    private javax.swing.JButton bVisualitzarOrdenats;
    private javax.swing.JTextArea eMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void mostrar(String text) {
        eMostrar.setText(text);
    }

    public void borrar() {
        eMostrar.setText("");
    }

    public void canvia(boolean activa) {
        bVisualitzarOrdenats.setEnabled(activa);
        bBorrar.setEnabled(activa);
        bClear.setEnabled(activa);
        bOrdenats.setEnabled(activa);
        bPalindroms.setEnabled(activa);
        bParaules.setEnabled(activa);
        bSenseRepetits.setEnabled(activa);
    }
}
